service: spotify-search-api

provider:
  name: aws
  region: us-west-2
  runtime: nodejs14.x

functions:
  get-spotify-token:
    handler: get-spotify-token/index.handler
    description: Get Spotify API token
    events:
      - http:
          path: /v1/get-spotify-token
          method: get

plugins:
  - serverless-offline
